<?xml version="1.0" encoding="UTF-8"?>
<blueprint xmlns="http://www.osgi.org/xmlns/blueprint/v1.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.osgi.org/xmlns/blueprint/v1.0.0 https://www.osgi.org/xmlns/blueprint/v1.0.0/blueprint.xsd              http://camel.apache.org/schema/blueprint http://camel.apache.org/schema/blueprint/camel-blueprint.xsd">
    <camelContext errorHandlerRef="myDeadLetterErrorHandler"
        id="errors-example-context" xmlns="http://camel.apache.org/schema/blueprint">
        <propertyPlaceholder id="placeholder" location="classpath:propiedades.properties"/>
        <onException>
            <exception>io.fabric8.quickstarts.errors.OrderValidationException</exception>
            <handled>
                <constant>true</constant>
            </handled>
            <log id="_log4" message="{{log.cuatro1}} ${file:name} {{log.cuatro2}}"/>
            <to uri="file:{{ruta.validacion}}"/>
        </onException>
        <route id="mainRoute">
            <from id="_from1" uri="file:{{ruta.principal}}"/>
            <log id="_log1" message="{{log.uno}} ${file:name}"/>
            <!-- VALIDAMOS LA FECHA DE ORDEN CON EL BEAN io.fabric8.quickstarts.errors.OrderService -->
            <to id="_to1" uri="bean:myOrderService?method=validateOrderDate"/>
            <!-- ARROJAMOS UNA EXCEPCION AL AZAR CON EL BEAN io.fabric8.quickstarts.errors.OrderService -->
            <to id="_to2" uri="bean:myOrderService?method=randomlyThrowRuntimeException"/>
			<!-- LO ENVIAMOS SI TODO ESTA BIEN A LA RUTA: work/errors/archivosCorrectos -->
            <to id="_to3" uri="file:{{ruta.bien}}"/>
            <log id="_log2" message="{{log.dos}} ${file:name}"/>
        </route>
        <route id="dlcRoute">
            <from id="_from2" uri="direct:deadletter"/>
            <log id="_log3" message="{{log.tres1}} ${file:name} {{log.tres2}}"/>
            <to id="_to4" uri="file:{{ruta.muerta}}"/>
        </route>
    </camelContext>
</blueprint>
